apiVersion: apps/v1
# Deployment kind
kind: Deployment
metadata:
  name: platforms-depl
# specifying the deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: zeray1919/platformservice:latest
