apiVersion: apps/v1

# Deployment kind
kind: Deployment
metadata:
  name: platforms-depl
# specifying the deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: zeray1919/platformservice:latest

---
apiVersion: v1
kind: Service
metadata:
  name: platforms-cluster-srv
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
    - name: platformservice
      protocol: TCP
      port: 80
      targetPort: 80
